Html and CSS files created for the first project.
Adesina-Abiodun/HELLO-MICROVERSE pull request #1
Opened 2023-04-25 23:03 UTC by Adesina-Abiodun

2023-04-25 23:30 UTC, Efiamotu-1 requested changes
Hi @Adesina-Abiodun , 

![](https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67)

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 23:30 UTC, Efiamotu-1 commented on .gitignore
> +text.md
- [ ] based on the requirement highlighted below you are supposed to ignore the file `test.md` not `text.md` kindly correct this typographical error :+1: 
- A test.md file with the text "This file should be ignored by git".
Make sure that the last file is actually ignored by git and is not present in your GitHub repository.

2023-04-25 23:30 UTC, Efiamotu-1 commented on index.html
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
- [ ] Make sure to also name your branches descriptively tailored to the changes you would be making for example `add-homepage`, `mobile-menu-feature` etc
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)

2023-04-25 23:30 UTC, Efiamotu-1 commented on index.html
- [ ] Your readme file MIT license link is currently broken, make sure you are linking the correct license file to ensure that the link doesn't break when clicked. visit this [Licence setup link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) and add a license file accordingly to your repo :+1: 
- [ ] you currently have two authors for your readme, kindly remove one and add your linkedIn and twitter handle as well. this will make it easy for recruiters and potential clients to reach out to you. :+1: 
- [ ] Kindly add your github repo to the `setup` section of your readme so that users can easily clone from the readme and set it up on their local devices :+1: 
- [ ] Put an information notifying users that there is currently no available live demo rather than just using a dot, it makes your readme look unprofessional :+1:

2023-04-27 08:05 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @Adesina-Abiodun  👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 08:05 UTC, abdulhamiid commented on README.md
> +### Twitter: https://twitter.com/adesinaabiodunp
The link to your `LinkedIn` profile is currently broken, kindly fix that. 💪

![image](https://user-images.githubusercontent.com/78251927/234798789-230a625b-fac5-4a83-96bb-4e092b79eb8a.png)

Let's avoid broken links in our readme file for a professional repository. 👍 🤗

2023-04-27 09:52 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Adesina-Abiodun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/c5fc4419b60b7a10d3cbd53b3c87385d07218531050477ca5810cd26a820c1c5/68747470733a2f2f6369352e676f6f676c6575736572636f6e74656e742e636f6d2f70726f78792f7a7138306d525a5670712d654168647a6d764e59502d4c4a6d4553563455326d434c6b55446a2d4a37374836464b42366f4c4f2d654c386b4746454e6c6e6b3135615151506e4a324b376853475a69615a42484d4b465a454d36794341543548306c654a78737a70694a5f5a52784e63354c3975763657663042465a556f6d5a5969594e3670706948676c744436716a635f4b68385262483362346e564c5067684a6c7066784d32394941695f7138646a6c6f78466d6351515f49326949595f725958565565426953664e735652666b30697133776f37355f6e66395148656a4e7335457763447770376e3476756b4156307246463678426e41656e49426c4a395f437553474e3337705a304644524f635f4c555f72496e6f687767443573544a6e4954557865587371356a75687535627445753041687471704656354d445654514d665a773d73302d642d65312d66742368747470733a2f2f63616d6f2e67697468756275736572636f6e74656e742e636f6d2f623465386630333565306632643230333032303334343032303236623864663637356533613964643933623732326431623061303437313132653638303434642f36383734373437303733336132663266363332653734363536653666373232653633366636643266346135323636353733393434346335333466373634313431343134313431343332663733363536313663326437333635363136633264366636363264363137303730373236663736363136633265363736393636" width="275px" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark: 
- [x]  Application works as expected :white_check_mark: 

## Optional suggestions
- [ Optional ] I've noticed that the first letters in your commit messages are not capitalized, I would like to suggest that in future projects you capitalize the first word in your commit messages this is usually a convention when writing commit messages.
  
  - Use _Edit readme file_ instead of _edit readme file_
  - Use _Add license_ instead of _add license_

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 09:57 UTC, merged

2023-07-03 14:41 UTC, joskalenda reviewed
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Adesina-Abiodun , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Great project implementation

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._